name: amity_sdk
description: The SDK that enables social features such as Feeds, Groups,
  Profiles, Content Posts, and Social Media Type Interactions
version: 0.36.0
homepage: https://amity.co
documentation: https://docs.amity.co/social/flutter-beta

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  byte_util: ^3.0.0
  collection: ^1.17.2
  dio: ^5.4.0
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # http: ^1.1.0
  mqtt_client: ^10.0.3
  path_provider: ^2.1.2
  socket_io_client: ^1.0.2
  uuid: ^4.3.3
  amity_sdk_api: ^0.0.3
# Add the lib from the pub dev before deploying
  # amity_api:
  #   path: ../amity_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_dotenv: ^5.1.0
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  lints: ^3.0.0
  mocktail: ^1.0.1

assets:
  - .env
  - dotenv
